import IConfigOptions from "./src/classes/IConfigOptions";
import ImageMIMEType from "./src/enums/ImageMIMEType";

export const config: IConfigOptions = {
    ipfsGateway: "https://apc.mypinata.cloud/ipfs/",
    renderMIMEType: ImageMIMEType.JPEG,
    maxPerRequest: 80, // 180 is good for RAM limited to 512Mb
    maxConcurrentPerRequest: 2,
    itemsCID: {
        "background": {
            "background-1": "QmasaaTYGqaLhuhqMTxr2FzbgTY2cr9azafhQiJHrQ6usy",
            "background-10": "QmVi2YhcCUn5F9TSRg57ebvo2BFGnRBqBtdrLz42L58bcZ",
            "background-2": "QmZyZ6LmiN5hm6HNDZbwBkCDibMZBoAmw5c84y2he5tSTU",
            "background-3": "QmeK9oC4fxW4m2ogg64Qf5WxeppnyTScZMncqtyeD9U6eK",
            "background-4": "QmTgrqNQurCrLPY1pTprTiVWY4sPrUxdfn5prvrmeJdKmB",
            "background-5": "QmQkD7X4ggZse6Vrnt9WLtKnZMaeWcziAQLhG6rkDU2F3n",
            "background-6": "QmYdvgoRdm2tB83R1cuAKPnnZTigMnYh25si44ecL1FZiT",
            "background-7": "QmPNZo4QmzeUb5xydV3V9fxk31LHvWj1Tv5aJq8Att7VGn",
            "background-8": "QmSaCMXBEHNf38SnFze8Nx92MZtCXUTsDFjXUBRPomSb4M",
            "background-9": "QmR4seovfkLMc9Mx16kxk7mLxavnu8mxoQFzpgH4DDeWot"
        },
        "beak": {
            "beak-bandana": "QmTpQx5Si16w7ePCZ2tqa7o3bxPsbJvWssWRGdPNHWxnbV",
            "beak-bitcoin": "QmbdGdr3TfPEpr5FycAzVe6tHf18nx4wo1xmmAudxRRMqS",
            "beak-blue-meth": "Qmb8d9ENAaMbvhXnnEo8yPoCUY55kKmV29rnakcp5MTKpt",
            "beak-bronze": "QmakhR6JXifmAbksKbXr6SDSFWq1qVLaHK7HZvvB1ZQLQX",
            "beak-chewing-gum": "QmYdh6XrLWAeQTirfdQ3TDtLJMX6U69NbJisUrywusSEXE",
            "beak-cigar": "QmTg56UG2HY2KHixcBCFUUpok6HE6quauLEDaQdqZPGS6s",
            "beak-cigarette": "QmUX1GYhtkgQnTDNhmAWX38L8eqnchnJeDpj1gBKrp9efm",
            "beak-classic": "Qmamqckr2cpqfXGfDroDZTY61k9by2tYAsw1HeBKEcAg8n",
            "beak-classic-orange-yellow": "QmdJzrkK17skt18SYT5dLQpNFNnnbMPAh3nkVUf9Fnv4X9",
            "beak-dagger": "QmcvzWkdmaB3K4gcGGrGZczshQcGMnaSf6rsF3Mm2VXswj",
            "beak-diamond": "QmaHwQPFJPvsuXTssFhtQMvd9SseuRx7GydyuiqZXXw3ST",
            "beak-eel": "QmcK5LGkdCEjFMYQcXwWM6rtLSvB1MGHyY1tp7MCvu71xB",
            "beak-egld": "Qmf5YAC25zBZK8hUp8KfZsaWPGWWJ7VwGdXGThEubfaitJ",
            "beak-flower": "QmWMmxA5qFU5mGPqTdja5LN6CTcwLaZ7HbXGjF66ad4fX9",
            "beak-gold": "QmfSxePAuhnxaMxAJRNPVkYy9xJL9TeVthbxxQchwPBCgh",
            "beak-hook": "QmegncydaWMsQCNs2smaQTyNif9tUyXNuLx1DYZGmzcJ6w",
            "beak-party-horn": "QmXjKJUW1D2mr9aUi3dcEs45snVmU4waV4jYDpm7piGBFW",
            "beak-pipe": "QmVsiopKUBVDTz5uXSfYeP9m34wFeCiLyXDkDrTkbsi8z9",
            "beak-pixel": "QmcttNfkLKPNFV3huhYLN9ppQdztm1jGquErv1nMHJHBFe",
            "beak-pizza": "QmZutD3eWQGDGCafTeEaE71iX3kTaNgbcgxLyGSHnHP5we",
            "beak-silver": "QmPLzLvV8H3kcrxfuoubkh95doYGM413UnQzG1Gj3pa82D",
            "beak-straw": "QmU7hVVLFVFqsGLQK57bPf4Fc8FrmUea5N8oVXzSTH9FBb",
            "beak-teeth": "Qmf5nXPW1BEu4kavtfPjLa5mJsi6hiBUc9oiZGQJHXugLM",
            "beak-toothpick": "QmeLH59YaXLmbaX6XnRFk8YSefXMdu24u29VuFgcxmCSYA",
            "beak-wine": "QmfLVjh51VJnxMT5uy54p3bPMZDKNk18554YG63vKeG5d6"
        },
        "clothes": {
            "clothes-basketball-jersey-red": "QmaTv2bmWaDnuQEgSaC8Xsak5g9YXdFLaPBcP5xeQfQ4yv",
            "clothes-basketball-jersey-yellow": "QmSf4gqtjVsVMt1pGTYyXx6oNKFDEy5BrEvWnr6vdVEzoE",
            "clothes-bikini": "QmYVYbUYAUkxXcZaBRSNcPax2oPyCrptKc9JpUXXfmg7tz",
            "clothes-bulletproof": "QmXxRkDbh2SAX8CdECtEGA2ZL3ZzD7v21cahsFvxoBEXDu",
            "clothes-bulletproof-harpoon": "QmXjWBM2tbtcnGYTbwHHKddAAD3rzzmx1DjwZFxKQG2okg",
            "clothes-bulletproof-holes": "QmQbHZJvWvSvDG9TAdiSZJzprGQ2hB6jxXtRMh4v3YpbM8",
            "clothes-coat-with-fur-black": "QmUp3SUhDeFNPHiThcW9VFihS3dzQbKZtGHP7f4EYdgiys",
            "clothes-coat-with-fur-blue": "QmafY7SFKeYYSdkNxoErvq4Qw7mgggVJzaCBzXjxWFc4vB",
            "clothes-coat-with-fur-brown": "Qmbgir4YBAfKwQt57RtBxuM2wBLjBFw6DUAsszNYzTnEzH",
            "clothes-coat-with-fur-red": "QmYjxDyKtBa6MfbPND8htB6o6YfrrtkAMtZtgifsR8isyn",
            "clothes-coat-with-fur-white": "QmZzD7cgHpjcvg2SfE5zA1CaiwUCMoZY92LzgDisPPSmtF",
            "clothes-diving-suit": "QmUhRGYkyoY23Kj7wSRJChLCvvXDqGwMdAzRmiHm8hoj2E",
            "clothes-duck-buoy": "QmYQsYVYt4r8Dw8Lnb5ZPwExLtWhyQpE8NELtubFtSc9Hr",
            "clothes-fisherman-vest": "QmR6j8tkBfyJdNnebogzMTGPfMG7hUY4MYy7YjzjQkM2Y4",
            "clothes-fishing-net-empty": "QmX4VSU8XHzX2tXCAKRVmkojgkEuQyZ1jws7BHCuHYUN8F",
            "clothes-fishing-net-fishes": "QmTfCa2qg3Vze8ocsWW51MbjFJmDmqiR9SduyoZZSaFWUo",
            "clothes-hawaii-shirt-blue": "QmYDNwh2v1UJmUFj6ddJxX1tqLTjcPdWbpfCRBAsMnH7wX",
            "clothes-hawaii-shirt-red": "QmNVS4q7G4cvS9q3LhZAVSd1D4CNqhZyiJNayAPWgkZCDf",
            "clothes-hawaii-shirt-yellow": "QmNmkZAzDKeznYyfqDUm1rWTbr2UYqw2Px8oSYzjYNXjNy",
            "clothes-hoodie-ap-black": "QmSmYK1uxvee5tkan8ERdk4e1zbKnqHrPabvBMH9vFdVPN",
            "clothes-hoodie-bitcoin-black": "QmQTGDmGaM1zevSZyyRHCj2wCT4a6iMma7WEkNzHuvKraQ",
            "clothes-hoodie-bunnyverse": "QmQjUVSBXS2A3ChPuuCTa699Ri3yDoyex3ndAiWBzzDSHP",
            "clothes-hoodie-egld-black": "QmNVvvW7dfUejxPBNnefuEHmHfnyyWbcZ5hmCsFXmUc6LP",
            "clothes-joker-vest": "QmfU99ndANQdVeRJNpZ2sqN9gZnbm59CUgfua46o2R41uw",
            "clothes-kimono-black-belt": "QmXeBGfUv6cuPZRtPzyiYSoPXceNML1Kbvdnke4Khu7Ayv",
            "clothes-kimono-red-belt": "QmXD8TYrFydZZmt7SjKdccDZixLTHpVVrx3jbDs3afCUBu",
            "clothes-lifebuoy": "QmNXMv1XDVUpaQX66ifd41CfXcYbvYQ5rwcioqqzEEi6LF",
            "clothes-lifeguard-shirt": "QmYVwcwmP1FdNcSAv14Wem1x4JsejXkAWA6bLnSAx3oxaw",
            "clothes-lifejacket-red": "QmZrgxKiwf89pwJ5DbNTzN4PA25ECfqLnaJASwFo5vfP6k",
            "clothes-lifejacket-yellow": "QmS9ay1JaZGsrcCD8ppYtuqPmWdSopvBvFTPAyohUFjucf",
            "clothes-sailor-jacket-black": "QmaHbBQH1WS7vFPVU5X5LkNgWvj1PwQKovaBHJp6mj83zQ",
            "clothes-sailor-jacket-blue": "QmR3fPKxtxUoJfK9UUWGSGzUbcrF1YcVPJpMx17S48Uknw",
            "clothes-sailor-jacket-green": "Qme4pLf14fVYFz12RZgowdw3aLMHTHyS3VuHWWt1dzvyPJ",
            "clothes-sailor-jacket-red": "QmUvjMK2auyy3PQGVacDp6h1HEw9EvyFidesvQE7g25HCM",
            "clothes-sailor-jacket-yellow": "QmXtZcpu3H3ZbguWFD7Bo2345KJx2yXZEBAignWL6shfSB",
            "clothes-t-shirt-ap": "QmTWtMsmLoAvrTo1NzFBizsjf9pKXBzxLBCBdtQ3jz35Dx",
            "clothes-t-shirt-bitcoin-black": "QmWqzQZXfzkfyp1USS5Vmh1erAAbLxDePrfZVVetvQtyax",
            "clothes-t-shirt-egld-black": "QmReqBAahRQ799C2etRUiQGsagDRuURbr5gEz1goFTUW7A",
            "clothes-wwwine": "QmRU7efDYrNGsZuGGu6NTs4KZVbnsomhJfgWsR4VekXwJ4",
            "chain-42": "QmUfGRhEaaJDycYixjFJfSxyg1GWsjiTxbhPWQHE5pQtaL",
            "chain-anarchist-logo": "QmScvi4tt3oNfL6Rb4CjDmVxavwD1BPeLki7ScXxwXAWZd",
            "chain-apc-gold": "QmQ1nn3vehf6U7NvhrejJMAYqDtXb7WZeTgpK7v6SxPtxd",
            "chain-apc-silver": "QmRz7xprL3jxzPwVt6nHYwkHzLATJVwSbYdrY9Ut4mRdLM",
            "chain-bitcoin-gold": "QmSQ6otL37TTqdq52e9arPvsFPv77XYyRSJc4ZxmapMWVz",
            "chain-bitcoin-silver": "QmeiEv7yc6G1i8vk8FDk7nyYVNdDJkNU8v3pwqPtKGY3Z1",
            "chain-black-panther": "QmYSMjdQqDbrrEiY5MyMdfbak9rmNkSS9CqsS7tSoUVdsU",
            "chain-eggs-gold": "QmUxoHxoaycU7w97QAhKGwAdY1p7Uwj8xsgYD72pPSMaiN",
            "chain-eggs-silver": "QmbRB2BSquwqnJ4t7ajyxezUZuV7tN1TFx9hpK1sFNT9A2",
            "chain-egld-gold": "QmNmPGJNWE77yjwCxjUe2hz9BFj9BQK7yprjeQcjTbYNdw",
            "chain-egld-silver": "QmTDvYTMykA2yF578s9ZMMnt71KtxSFc5qGufuVdvyHvdF",
            "chain-emperor": "QmeqAKHvhi33YuQiXaQxYDZo6nHY9NETzvvxJiMG2F5eNR",
            "chain-fish": "QmU3czUxsp9tRAE4iUqGv4kjC9QXSiRQs34mwPoM9LE757",
            "chain-fish-bone": "QmQ65bbUyehz7vRoxs4R6EXk76Z2BuBDCfL2jhiSJTNMWe",
            "chain-flowers-blue": "QmTJUGYzjsyeXhXvrcNsuDfLWqQXnZUJXidmJr4joWYZdf",
            "chain-flowers-pink": "QmchEFra9U41EaXBRwhGypvRFqNSENzghf9Y7UAYcT5ydR",
            "chain-flowers-yellow": "QmSeFHcoq221AD8U8r3WJujMQ3DS6bU5snHs2X8GPphpUi",
            "chain-gold": "QmXodUdzNt6Q62s7Q8d1GmfSqSBoAVTRuFtMGhxbVKheY6",
            "chain-ice-cream": "QmXZCaiwPpymizRhEE62yfbChNCjLReqU9NsxWJrd1L4hx",
            "chain-lord-of-the-rings": "QmXc3utUFQt7wpJ4szYpZitfwJ5qn4kDkewtqmsA3hvnsK",
            "chain-pearls": "QmYV68gXGaMWHY79E32fBJTfUk6xYBVP69SmbVCiie7B6W",
            "chain-penguin-gold": "QmeuKBtfaQuDGTbRdRCvHobnrpD53s7BcSUKvfBNYtWnSt",
            "chain-penguin-silver": "Qmem8iwtSXgFiP7BkZa4Nvr6NZkB7CnEeGkAi6RSDq2nxR",
            "chain-plastic-bag": "QmS7RoWThFw5qxFfjVZ3tzmSUcyYc7CKk4VCwehAe2MbM8",
            "chain-plastic-packaging": "QmT6B1Jvuru5wQKXjHW5aNjM1b3Q6FEkmEBK6A9upZT5t1",
            "chain-prime-emperor": "QmYKLKfCzqPYf2vamm2UCR8VR7DSvmWZB3LVjJLyrBK9jQ",
            "chain-silver": "QmdFmyRsEQWSFX874MAfPNU9GMPk2xjz7JZGQCvdK8RsER",
            "chain-straw-gold": "QmPh1MMQr2DWeKvp7B7mGxkUNc7tCU1a4fczNwHdC5nQ4T",
            "chain-straw-silver": "QmNLu6MhBzxEiNTzTWiPWAhk8E7wU2bdJvw5HkdUHEwnqJ",
            "chain-weed": "QmaCJVBYdBFsXmVN8j8wHhk2wjzDXQUy6dmq4dAq9JuhKA"
        },
        "eyes": {
            "eyes-bitcoin": "QmSCwDU723r6DQirKPE8KhAScvh9vVe3PABbaoSZUbuxzR",
            "eyes-black": "QmdXLCj5sviHAoHRysDEQmSGPTPJws3KkXnL4mZRJimi4C",
            "eyes-blue": "QmPUEmC6QnBehS1d5H4ovXiBNBdyCW8gMCVE71JYtj4c35",
            "eyes-classic": "QmaapjJRWBzUvgGfJLdkFtjdBRZCvyPkv7oSM9xxbehDJq",
            "eyes-crying": "QmP5NcPfjP5P2WbffTtW6ZjBqCAw4F8b5XTzVLTyDiiaCP",
            "eyes-egld-coin": "Qmc1p7fXUPgKLDSWaHhXXHSk54yPazTWF6qb6MDG8n6RKH",
            "eyes-glassy": "QmZZMcfXNvESfhgxsxHMLU8aAbL6DEYRftgsF6SDT6xuYB",
            "eyes-green": "QmaXxKxWFjVWts1Qw77S2Ph4yvJyVx4pGvHP98znVLPDpd",
            "eyes-hanging": "QmRdQdBNVqMRUg1kCK1qNHU9G6A7bSz65AYjQhMFA4FXGZ",
            "eyes-headband-green": "QmQrmdbuTeC648nVcn3vpj3d8zpfi2dPfred2joHMEpsrn",
            "eyes-headband-orange": "QmZKzn8i1snHcBdQzsB1KQbma2ANgYW4L5ELJJhhwZh2ih",
            "eyes-headband-purple": "QmUFvpJXRnmrxyrVHcJ1G4Na6xuC3y6q4rzg3zCzS8NcQz",
            "eyes-headband-red": "QmYMGEeMNbHuCFQ8ooxgCTELxdSu2TjZGMzFpNpw4BPw9D",
            "eyes-missing": "QmUbZqRqsZtpCgBhpb7JrK8xwQt8YQbo7jxBjAfPhSkPnn",
            "eyes-red": "QmZuMCPzh54q12cV9VEUb4CC8eHbBUQjQC4esXBTUxEcSm",
            "eyes-snake": "QmQCndFgCMpbYyWN1YQ22fSWzJfT2spKB9v1osP7XVeWf3",
            "eyes-strabismus": "QmSoWhouECZEL1Fm2LfnaJWqffaQdCzqytfPwv3CTqJHtU",
            "eyes-white": "QmYm6cbM5b1Cn6yQnU3b7HtGipv1HzkjnLknLdxKer7QYz"
        },
        "hat": {
            "hat-algae-brown": "QmbR7BBk5d71KktKiuXqS77UyvhrGjnnYM9Y1gycZFH1E4",
            "hat-algae-green": "QmbEk2pq92gERc6XxdVdj4wPQReHc9HfBpZCj6Q8MEy1y9",
            "hat-algae-neon": "QmVmAtB1cWBJvP61cF96W4JsfCBuWkjK7Kvjc6Tz14YQ5G",
            "hat-anchor": "QmNaKPRfWt5oPkozP92HqaxZYZYuaVom2SgKbJcGG1E7zS",
            "hat-beret": "QmR8jehRV2UNdxXFVzB2yK1oUh8gKxxjMHoMM5WBGuAiri",
            "hat-bull-horns": "QmQZXuCiqoPvxwpGvog7vSNmm6YPyMoKhjdRSN25yW1NFB",
            "hat-cap-apc-black": "QmbTeQdUcunaqTKRAyDqk8RXYEyVLCDPHJr8m7XqFTEYyj",
            "hat-cap-apc-blue": "QmUmu6jxDvq8YG65yLS9hWdPXR7zpdf2D9mqtwck59fpCz",
            "hat-cap-apc-red": "QmfJpNpJNbRwfzzZHsAqT5N3GwbU4zkwgqYR2PBvUwHMeJ",
            "hat-cap-apc-white": "Qmc5KnXopAXNYEqfD45XFSn2wNL55EbMjVQGPdSFK78o8v",
            "hat-cap-beer": "QmWpqkCk6hfiYUxd8QQUh5SjiCqotQg5RCT8BtwyV3FEVy",
            "hat-cap-bitcoin-black": "QmTLjpZuJDJh3pFhTSA5PUk7csAMoMkG9pHaaaJFSeNSit",
            "hat-cap-bitcoin-blue": "QmZ9QYmEk7y9Ep1EVcjFgdeEF3FdHdshChjtozxVbewrK2",
            "hat-cap-bitcoin-red": "QmP1ToS4iwZrsZkAsBMYcC7QR5Kewx8kojGFvH8jCkx2J6",
            "hat-cap-bitcoin-white": "QmeV5hawLiEL8vgPYVEPmQjEYkiefvtHBJCGWHdwTSp4kn",
            "hat-cap-egld-black": "QmeKyc3jaBUJKWge7AhXDBCdZbJGsmHtXt6ZAJPpzKnfLB",
            "hat-cap-egld-blue": "QmcuJhfpkY9QxayCbaTUiwYoYzG8VmVaebCewufze2m9Dv",
            "hat-cap-egld-red": "QmcjnmVLoBX6HwWdWBykkT4Vt7XiDHNiXUq7Coz1R9xSFk",
            "hat-cap-egld-white": "QmUJBtKH93AKrz27TtEnisPcD3sJLNU3S7bqxbwD7X1o6L",
            "hat-cap-propeller": "QmS1PptqaenV5P3cMcAcQBu9rbCXGNmY2iYdf2jnu6ZoFu",
            "hat-captain-black": "QmY7WAa7GTJBHb8APMsYdZZ2FNWLsz8z84D1ndNntA8k3Y",
            "hat-captain-gold": "QmckLyN7pHBDCUGrwQ9zCqYKNdFT7K41YvoXmCawS1hgyD",
            "hat-captain-silver": "QmUCh5LVvmLakwUFHBMShSTFLk4YiB1GSgPnAf7VUJKgBv",
            "hat-chapka": "Qma2aRsbhsU8834EKxAr4U8AZhLx74Xh5LoGJWJzRmiERa",
            "hat-cowboy": "QmXu98nVxXnxHWecTrD6zvXztQfZTkfgDG1zA2Bw2FQzYB",
            "hat-crown": "QmRjbMH9JzPNSXexQZAxPpB7GfQuYVLvj1dZrjFXCm7eeH",
            "hat-headscarf-pirate-apc": "QmTadRt7guX2a9JXSpPtNUvdX5By5kMUTu2xLCpWNgMpdQ",
            "hat-headscarf-pirate-bitcoin": "QmVnsFtytQzVphunmtJ8bQKkbAVLMUdTtD47itP9mnLUaH",
            "hat-headscarf-pirate-egld": "QmWPj2Zsr9N5s5rbEVGLo5K3TUvcDTfedNetqFqDzdr3Jv",
            "hat-heisenberg": "QmUn3q4WCAxLjr9XZhGUHLBML9qx7B889doAprLJmzfMxS",
            "hat-igloo": "QmRHNaphFaxdb69WNZwJdgG8ek8NfDYJPJggTL7fAftJbY",
            "hat-joker": "QmeBMx5nwStTPCArNrNtHFpSgFiPTLXb6TzzaJqNzUkBxK",
            "hat-laurels-gold": "Qman6S7HN1ieEi1LNMcMuf5JuQuQk67jBjdUwdkZuLKdUd",
            "hat-nest": "QmRuQPTfFhzM2rXXXDFiFHBeVdfZNFg3WcF4ds3nDiMpsv",
            "hat-octopus": "QmZYbkt7bsAJcDhPvqjCkrbgsjzoEL1BtRvjM7Wyg9qKPc",
            "hat-pirate": "QmV1pKoxB3jievoLj19cGFueMWcvzpzpZNPkP3c5XABhgr",
            "hat-plastic-bag": "QmdJpeVCTLK9mJZtZnk2Sks2dTKUZPuLDBhJuNRAkMsrK6",
            "hat-punk": "QmNyQdsWV6LWqnj8wnT6ZEb4LAx4EFcXQg4cFxLXHEtStU",
            "hat-sombrero": "QmQp69SW6AvYf6xUE8cvwWQDjzasYvq8LNMkQsdt2YRVDs",
            "hat-tiara": "Qmf7xQH7QZSgV7wm7gCTcv21wwBKT3gJn4XG4ehs1CY3PH",
            "hat-tonneau": "QmSz6HeM9BxegB9PyTci7a3gzDwULMmhkWfzmh1Z1cJged"
        },
        "skin": {
            "skin-albino": "QmTWBzNHvH2znUWsY3W6SuSzK9mnREA8m5oMxfhZRxGV9u",
            "skin-aquaverse": "QmdYLd41Rtve45iFs6Rmz5GoQGnKh9dVZFceWTKk1CvQq6",
            "skin-black": "Qmf6SFCsUpbWw6kNnTE8fKPd8diVegLDAFzWsjKzQHitGk",
            "skin-bronze": "QmZvcL2W6EG3tUJpb69CuwGWwSqBe4cCfBQRjvPv83pggu",
            "skin-crocodile": "QmQyZZmAfRqadoKypZng4TxNvqc8S4nZScFqg5bbTxb47D",
            "skin-diamond": "QmWc1Tx12hwF3J6dnNE8zuLig5EtWxMeM2ucT1za4VKcL1",
            "skin-frozen-dark": "QmWBPpVLUV1M3tAragWU4GGsgs5zYrdhkTRiFBd7c9PERx",
            "skin-gold": "QmQqsRggYva588Pkx9knPTCv4A1j5AWY6MXGgNgBXxNMPW",
            "skin-leopard": "QmZf6qCuLbmkJEiAFcUANMEQSHn4GRLGGsgp9XwgDR8dyy",
            "skin-oil": "QmY964XLCa5LZsj2H5NNNueJ92geavWikce55RmGHzJgQN",
            "skin-original": "QmdBbSbwW9Ho7Yk2sKLnV8bbvrwLzJfhLUejQpH7CvGkik",
            "skin-parrot": "QmZgayy91DYumg4E5j9YnCzu3htLxLL6xieRPjmgxJZsz7",
            "skin-pink": "QmRDwrQqkk9Yg5Xm1Wywn4YHcJDahha6ExTxh5CbGskZ1F",
            "skin-pixel": "QmR3VLifKkybceG3wRtjnVR41qQu76UPgiMyAZZx2Snsc5",
            "skin-reversed": "QmVJTAft4K5dkmtRfbYrHJX3JkkuRGVbNag1Aw57qbwrXT",
            "skin-robot": "QmacJYxT91XKcXZ1HWePyLYaU4f3wRfw5rKry636FfGtjE",
            "skin-silver": "QmNxw6mxJXg6vZcfDyPpW3P6kaWm1rYmzSpLscUjNaRmEW",
            "skin-tiger": "QmXnkZzARjcb4oCyDd56tDh6Jjg6jVGHYbhg7XSyUK95EU",
            "skin-wounded-1": "QmdJysyhm78NCEh2z2aUNbNK4fAt3KRHPowabo6wq4p1H3",
            "skin-wounded-2": "QmRXkZe8R9c9JikexviPzSMcnS4AvdAdUcA5tAb3iv4SdB",
            "skin-wounded-3": "QmWA1uMGVevoFT7MKQBJa1Lo9HxW8uW33m1KeTbDrnsBzd",
            "skin-yellow-parts": "Qmc5NdfFLvQqbrTyBig8Wx3iEVpisG2cCL58NujJahu2jE",
            "skin-zebra": "QmQQKW3DDjGqqBHT6wjjh4oVuJyRGeEzFTiKpBKsQJTG77"
        },
        "weapon": {
            "weapon-axe": "QmPoMVTK8Bc54Lus5BjZv9jDnvi54fLZ2CQvMmKvhZ6yjG",
            "weapon-bazooka": "QmeEMYr9QC9QDmy5x6YmsvxpqEbv7gunVPw3iDuGZB9a82",
            "weapon-bow": "QmPux3XGx7jhLgBuAGxmS9Yk3LEiXUMNDeC77naPX4Z7fN",
            "weapon-crossbow": "QmRe44VKJtcKHf37DCDeJ4J7YnXK3zej2tz3UyUqKi5pat",
            "weapon-fishing-rifle": "Qma2sg2B6YjD7nEA25uMEiyGbrJfb416xpCd1gNnqjNiAC",
            "weapon-fishing-rod": "QmS5ZgEPZZCjMq8EUwxNNAFsEEwSmQabtMaajMWPQKPj1g",
            "weapon-flamethrower": "QmS1zAqbSGiQXHwvj6wPLD2ZFQX9nZgnVE4qMZYQWfkyW7",
            "weapon-flashlight": "QmWyX37QZ1juVtpNTEGkxCR9TbTrrXM4i2DrBXnnLA3K7q",
            "weapon-machine-gun": "QmUZ3JR7itkWerkbhYp2778B3vUK4xDzDgfVwNfHffoFzM",
            "weapon-oxygen-tank": "QmSA8AHvLPUHGvUk8xaaF464QKZXnSiq7yhikv96ScXuhm",
            "weapon-sea-shepherd-gaff": "QmdiEwK1gMRYSQnQqxvdwSDh9ajKwzR2BURJMNDH1YojqU",
            "weapon-snowboard": "Qmbco5KmijqL9cRuf5aKEq9VbvHrH74UvJFAovHBmtp7hf",
            "weapon-spear": "QmTjFTG8eQHBHsfwBDWtpkDVSLwwWQbk9FA5XpRqeiqWaG",
            "weapon-spear-frost": "QmYzvAHR8KTeYWYPHEmDz3GweGPZxTYrpTwcnXhXirxn8L",
            "weapon-surfboard": "QmZr6fafDoATy3H7RPUD7f4H6iDSTBGYxqwttCG4QkMDo6",
            "weapon-tomahawk": "QmZqDJ5MfNG89xsaPZLjwWmSDJopB2R3TYzYqppmLL4J9Y",
            "weapon-trident": "QmfE9NpEZFL5q6eUvLq5DnJzGVunq5U5ecTFtKwwWcLaDy"
        }
    },
    layersOrder: [
        "background",
        "weapon",
        "skin",
        "clothes",
        "beak",
        "hat",
        "eyes",
        "badge",
    ],
    defaultLayers: {
        "beak": "beak-classic",
        "skin": "skin-original",
        "eyes": "eyes-classic",
        "background": "background-1",
    },

};